package edifact

// UN/EDIFACT D.21A code list 3139 (Contact function, coded) -- the real
// values CTA's "Contact function code" component (see
// segment_elements_data.go) can take.
//
// Source: https://service.unece.org/trade/untdid/d21a/tred/tred3139.htm
// section "Code Values". That URL 403s via Cloudflare when fetched
// directly; this data was extracted from the Wayback Machine's archived
// copy instead:
// http://web.archive.org/web/20221123154249/https://service.unece.org/trade/untdid/d21a/tred/tred3139.htm
// -- re-check the direct URL first if cross-checking later.
//
// Extracted mechanically the same way as codelist_1225.go, by the same
// script (extract_codelist.py's approach: parse the "Code Values:"
// section, stop before the "Data Element Cross Reference" footer).
func init() {
	RegisterCodeList("3139", codeList3139)
}

var codeList3139 = map[string]CodedValue{
	"AA":  {Name: "Insurance contact", Description: "Department/person to contact for matters regarding insurance."},
	"AB":  {Name: "Workshop contact", Description: "Department/person to contact for matters regarding the workshop."},
	"AC":  {Name: "Accepting contact", Description: "Department/person in charge of accepting incoming goods."},
	"AD":  {Name: "Accounting contact", Description: "The contact responsible for accounting matters."},
	"AE":  {Name: "Contract contact", Description: "Department/person to contact for matters regarding contracts."},
	"AF":  {Name: "Land registry contact", Description: "Department/person to contact for matters regarding land registry."},
	"AG":  {Name: "Agent", Description: "Department/person of the agent which acts on behalf of another party."},
	"AH":  {Name: "Coordination contact", Description: "Department/person to contact for matters regarding technical coordination of works."},
	"AI":  {Name: "Project management contact", Description: "Department/person to contact for matters regarding project management on behalf of the contractor."},
	"AJ":  {Name: "Investment contact", Description: "Department/person to contact for matters regarding investments."},
	"AK":  {Name: "Works management contact", Description: "Department/person to contact for matters regarding management of works on behalf of the owner."},
	"AL":  {Name: "Personnel contact", Description: "Department/person to contact for matters regarding personnel (human resources)."},
	"AM":  {Name: "Claims contact", Description: "Department/person to contact for matters regarding claims."},
	"AN":  {Name: "Laboratory contact", Description: "Department/person to contact for laboratory matters."},
	"AO":  {Name: "Plant/equipment contact", Description: "Department/person to contact for matters regarding plant/equipment."},
	"AP":  {Name: "Accounts payable contact", Description: "Department/person responsible for the accounts payable function within a corporation."},
	"AQ":  {Name: "Quantity surveyor contact", Description: "Department/person to contact for matters regarding quantity surveying."},
	"AR":  {Name: "Accounts receivable contact", Description: "Department/person responsible for the accounts receivable within a corporation."},
	"AS":  {Name: "Public relations contact", Description: "Department/person to contact for matters regarding public relations."},
	"AT":  {Name: "Technical contact", Description: "Department/person to contact for matters regarding technical issues."},
	"AU":  {Name: "City works authority contact", Description: "Department/person to contact for matters regarding city works."},
	"AV":  {Name: "Maintenance contact", Description: "Department/person to contact for matters regarding maintenance."},
	"AW":  {Name: "Town planning contact", Description: "Department/person to contact for matters regarding town planning."},
	"AX":  {Name: "Traffic authority contact", Description: "Department/person to contact for matters regarding traffic."},
	"AY":  {Name: "Electricity supply contact", Description: "Department/person to contact for matters regarding electricity supply."},
	"AZ":  {Name: "Gas supply contact", Description: "Department/person to contact for matters regarding gas supply."},
	"BA":  {Name: "Water supply contact", Description: "Department/person to contact for matters regarding water supply."},
	"BB":  {Name: "Telecommunications network contact", Description: "Department/person to contact for matters regarding telecommunications network."},
	"BC":  {Name: "Banking contact", Description: "Contact person for bank."},
	"BD":  {Name: "New developments contact", Description: "Department/person to contact for matters regarding new developments (e.g. construction)."},
	"BE":  {Name: "Transport infrastructure authority", Description: "Department/person to contact for matters regarding transport infrastructure."},
	"BF":  {Name: "Service contact", Description: "Department/person to be contacted in service matters."},
	"BG":  {Name: "Auditing contact", Description: "Department or person to contact with regard to auditing."},
	"BH":  {Name: "Legal auditing contact", Description: "Department or person to contact with regard to legal auditing."},
	"BI":  {Name: "Software house contact", Description: "Department or person to contact with regard to software house."},
	"BJ":  {Name: "Department or person responsible for processing purchase", Description: "order Identification of the department or person responsible for the processing of purchase orders."},
	"BK":  {Name: "Electronic data interchange coordinator", Description: "Code specifying a person responsible for the coordination of matters related to the exchange of information in electronic data interchange format."},
	"BL":  {Name: "Waiver contact", Description: "Code specifying a party knowledgeable about a waiver."},
	"BM":  {Name: "Automated clearing house (ACH) contact", Description: "Code specifying a person to be contacted at an automated clearing house."},
	"BN":  {Name: "Certification contact", Description: "Code specifying a contact with knowledge of a certification action."},
	"BO":  {Name: "After business hours contact", Description: "Department/person to contact after normal working hours."},
	"BP":  {Name: "Company Security Officers 24-hour contact", Description: "The round the clock contact of the Company Security Officer who is responsible for the vessel."},
	"BQ":  {Name: "Agent of ship at the intended port of arrival", Description: "Contact details of the agent of the ship at the intended port of arrival."},
	"BR":  {Name: "Cook", Description: "Person responsible for cooking."},
	"BS":  {Name: "Customer contact", Description: "The main department/person to be contacted at the customer."},
	"BT":  {Name: "Meter access contact", Description: "Department/person to contact for matters regarding meter reading, including access to the meter."},
	"BU":  {Name: "Ultimate consignee", Description: "Final recipient of the consignment."},
	"CA":  {Name: "Carrier", Description: "(3126) Party undertaking or arranging transport of goods between named points."},
	"CB":  {Name: "Changed by", Description: "Person who made the change."},
	"CC":  {Name: "Responsible person for information production", Description: "Responsible person to contact for matters regarding the production of information."},
	"CD":  {Name: "Responsible person for information dissemination", Description: "Responsible person to contact for matters regarding information dissemination."},
	"CE":  {Name: "Head of unit for computer data processing", Description: "Head of unit to contact for matters regarding computer data processing."},
	"CF":  {Name: "Head of unit for information production", Description: "Head of unit to contact for matters regarding the production of information."},
	"CG":  {Name: "Head of unit for information dissemination", Description: "Head of unit to contact for matters regarding dissemination of information."},
	"CN":  {Name: "Consignee", Description: "(3132) Party to which goods are consigned."},
	"CO":  {Name: "Consignor", Description: "(3336) Party which, by contract with a carrier, consigns or sends goods with the carrier, or has them conveyed by him. Synonym: shipper/sender."},
	"CP":  {Name: "Responsible person for computer data processing", Description: "Responsible person to contact for matters regarding computer data processing."},
	"CR":  {Name: "Customer relations", Description: "Individual responsible for customer relations."},
	"CW":  {Name: "Confirmed with", Description: "Person with whom the contents of the purchase order has been discussed and agreed (e.g. by telephone) prior to the sending of this message."},
	"DE":  {Name: "Department/employee to execute export procedures", Description: "Department/employee which/who executes export procedures."},
	"DI":  {Name: "Department/employee to execute import procedures", Description: "Department/employee which/who executes import procedures."},
	"DL":  {Name: "Delivery contact", Description: "Department/person responsible for delivery."},
	"EB":  {Name: "Entered by", Description: "Name of an individual who made the entry."},
	"EC":  {Name: "Education coordinator", Description: "Person in charge of coordination of education."},
	"ED":  {Name: "Engineering contact", Description: "Department/person to contact for matters regarding engineering."},
	"EX":  {Name: "Expeditor", Description: "The contact for expediting."},
	"GR":  {Name: "Goods receiving contact", Description: "Department/person responsible for receiving the goods at the place of delivery."},
	"HE":  {Name: "Emergency dangerous goods contact", Description: "[3058] Party who is to be contacted to intervene in case of emergency."},
	"HG":  {Name: "Dangerous goods contact", Description: "[3060] Department/person to be contacted for details about the transportation of dangerous goods/hazardous material."},
	"HM":  {Name: "Hazardous material contact", Description: "Department/person responsible for hazardous material control."},
	"IC":  {Name: "Information contact", Description: "Department/person to contact for questions regarding transactions."},
	"IN":  {Name: "Insurer contact", Description: "Department/employee to be contacted at the insurer."},
	"LB":  {Name: "Place of delivery contact", Description: "Department/employee to be contacted at the place of delivery."},
	"LO":  {Name: "Place of collection contact", Description: "Department/employee to be contacted at the place of collection."},
	"MC":  {Name: "Material control contact", Description: "Department/person responsible for the controlling/inspection of goods."},
	"MD":  {Name: "Material disposition contact", Description: "Department/person responsible for the disposition/scheduling of goods."},
	"MH":  {Name: "Material handling contact", Description: "Department/employee to be contacted for material handling."},
	"MR":  {Name: "Message recipient contact", Description: "Department/employee to be contacted at the message recipient."},
	"MS":  {Name: "Message sender contact", Description: "Department/employee to be contacted at the message sender."},
	"NT":  {Name: "Notification contact", Description: "Department/employee to be notified."},
	"OC":  {Name: "Order contact", Description: "An individual to contact for questions regarding this order."},
	"PA":  {Name: "Prototype coordinator", Description: "Department/employee to be contacted as prototype co- ordinator."},
	"PD":  {Name: "Purchasing contact", Description: "Department/person responsible for issuing this purchase order."},
	"PE":  {Name: "Payee contact", Description: "Department/employee to be contacted at the payee."},
	"PM":  {Name: "Product management contact", Description: "Department/person to contact for questions regarding this order."},
	"QA":  {Name: "Quality assurance contact", Description: "Quality assurance contact within an organization."},
	"QC":  {Name: "Quality coordinator contact", Description: "Quality coordinator contact within an organization."},
	"RD":  {Name: "Receiving dock contact", Description: "The receiving dock contact within an organization."},
	"RP":  {Name: "Authorized responsible person", Description: "Responsible person who is authorized to sign official documents."},
	"SA":  {Name: "Sales administration", Description: "Name of the sales administration contact within a corporation."},
	"SC":  {Name: "Schedule contact", Description: "Name of the scheduling contact within a corporation."},
	"SD":  {Name: "Shipping contact", Description: "The shipping department contact within an organization."},
	"SR":  {Name: "Sales representative or department", Description: "The sales representative or department contact within an organization."},
	"SU":  {Name: "Supplier contact", Description: "Department/person to be contacted at the supplier."},
	"TA":  {Name: "Traffic administrator", Description: "The traffic administrator contact within an organization."},
	"TD":  {Name: "Test contact", Description: "Department/person responsible for testing contact."},
	"TI":  {Name: "Technical documentation recipient", Description: "Department/person to receive technical documentation."},
	"TR":  {Name: "Transport contact", Description: "Department/person in charge of transportation."},
	"WH":  {Name: "Warehouse", Description: "The warehouse contact within an organization."},
	"WI":  {Name: "Alternate contact", Description: "Alternate department or person to contact."},
	"WJ":  {Name: "Office Manager", Description: "An individual responsible for managing the day to day activities of an office."},
	"WK":  {Name: "Chartered accountant contact", Description: "Code identifying a chartered accountant contact."},
	"ZZZ": {Name: "Mutually defined", Description: "A code assigned within a code list to be used on an interim basis and as defined among trading partners until a precise code can be assigned to the code list."},
}
