/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 30
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 15
#define ALIAS_COUNT 0
#define TOKEN_COUNT 7
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 9
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_una_advice = 1,
  anon_sym_COLON = 2,
  anon_sym_PLUS = 3,
  sym_segment_tag = 4,
  sym_data = 5,
  sym_terminator = 6,
  sym_source_file = 7,
  sym_segment = 8,
  sym_element = 9,
  sym_component = 10,
  aux_sym_source_file_repeat1 = 11,
  aux_sym_segment_repeat1 = 12,
  aux_sym_segment_repeat2 = 13,
  aux_sym_element_repeat1 = 14,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_una_advice] = "una_advice",
  [anon_sym_COLON] = ":",
  [anon_sym_PLUS] = "+",
  [sym_segment_tag] = "segment_tag",
  [sym_data] = "data",
  [sym_terminator] = "terminator",
  [sym_source_file] = "source_file",
  [sym_segment] = "segment",
  [sym_element] = "element",
  [sym_component] = "component",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_segment_repeat1] = "segment_repeat1",
  [aux_sym_segment_repeat2] = "segment_repeat2",
  [aux_sym_element_repeat1] = "element_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_una_advice] = sym_una_advice,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [sym_segment_tag] = sym_segment_tag,
  [sym_data] = sym_data,
  [sym_terminator] = sym_terminator,
  [sym_source_file] = sym_source_file,
  [sym_segment] = sym_segment,
  [sym_element] = sym_element,
  [sym_component] = sym_component,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_segment_repeat1] = aux_sym_segment_repeat1,
  [aux_sym_segment_repeat2] = aux_sym_segment_repeat2,
  [aux_sym_element_repeat1] = aux_sym_element_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_una_advice] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [sym_segment_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_data] = {
    .visible = true,
    .named = true,
  },
  [sym_terminator] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_segment] = {
    .visible = true,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_component] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_segment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_segment_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_element_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_control_number = 1,
  field_element = 2,
  field_tag = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_control_number] = "control_number",
  [field_element] = "element",
  [field_tag] = "tag",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 2},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 2},
  [7] = {.index = 9, .length = 2},
  [8] = {.index = 11, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_tag, 0},
  [1] =
    {field_control_number, 1},
  [2] =
    {field_element, 1},
  [3] =
    {field_control_number, 1, .inherited = true},
    {field_tag, 0},
  [5] =
    {field_control_number, 0, .inherited = true},
    {field_control_number, 1, .inherited = true},
  [7] =
    {field_element, 1, .inherited = true},
    {field_tag, 0},
  [9] =
    {field_element, 0, .inherited = true},
    {field_element, 1, .inherited = true},
  [11] =
    {field_control_number, 1, .inherited = true},
    {field_element, 2, .inherited = true},
    {field_tag, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(23);
      if (lookahead == '\n') SKIP(0);
      if (lookahead == '\r') SKIP(18);
      if (lookahead == '\'') ADVANCE(43);
      if (lookahead == '+') ADVANCE(28);
      if (lookahead == ':') ADVANCE(27);
      if (lookahead == '?') ADVANCE(7);
      if (lookahead == 'U') ADVANCE(34);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(36);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(2);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2);
      if (lookahead == '\r') SKIP(1);
      if (lookahead == '\'') ADVANCE(43);
      if (lookahead == '+') ADVANCE(28);
      if (lookahead == ':') ADVANCE(27);
      if (lookahead == '?') ADVANCE(7);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 3:
      if (lookahead == 'A') ADVANCE(32);
      if (('B' <= lookahead && lookahead <= 'Z')) ADVANCE(29);
      END_STATE();
    case 4:
      if (lookahead == 'N') ADVANCE(3);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(5);
      END_STATE();
    case 5:
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(29);
      END_STATE();
    case 6:
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(5);
      END_STATE();
    case 7:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 8:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(25);
      END_STATE();
    case 9:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(24);
      END_STATE();
    case 10:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(38);
      END_STATE();
    case 11:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(9);
      END_STATE();
    case 12:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    case 13:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(11);
      END_STATE();
    case 14:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(40);
      END_STATE();
    case 15:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(42);
      END_STATE();
    case 16:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(13);
      END_STATE();
    case 17:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(16);
      END_STATE();
    case 18:
      if (eof) ADVANCE(23);
      if (lookahead == '\n') SKIP(0);
      END_STATE();
    case 19:
      if (eof) ADVANCE(23);
      if (lookahead == '\n') SKIP(20);
      END_STATE();
    case 20:
      if (eof) ADVANCE(23);
      if (lookahead == '\n') SKIP(20);
      if (lookahead == '\r') SKIP(19);
      if (lookahead == 'U') ADVANCE(4);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(6);
      END_STATE();
    case 21:
      if (eof) ADVANCE(23);
      if (lookahead == '\n') SKIP(22);
      END_STATE();
    case 22:
      if (eof) ADVANCE(23);
      if (lookahead == '\n') SKIP(22);
      if (lookahead == '\r') SKIP(21);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(6);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_una_advice);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_una_advice);
      if (lookahead == '?') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '\'' &&
          lookahead != '+' &&
          lookahead != ':') ADVANCE(37);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_una_advice);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_segment_tag);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_segment_tag);
      if (lookahead == '?') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '\'' &&
          lookahead != '+' &&
          lookahead != ':') ADVANCE(37);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_segment_tag);
      if (lookahead == '?') ADVANCE(15);
      if (lookahead == '\r' ||
          lookahead == '\'' ||
          lookahead == '+' ||
          lookahead == ':') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(41);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_segment_tag);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(17);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_data);
      if (lookahead == '?') ADVANCE(7);
      if (lookahead == 'A') ADVANCE(31);
      if (('B' <= lookahead && lookahead <= 'Z')) ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '\'' &&
          lookahead != '+' &&
          lookahead != ':') ADVANCE(37);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_data);
      if (lookahead == '?') ADVANCE(7);
      if (lookahead == 'N') ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '\'' &&
          lookahead != '+' &&
          lookahead != ':') ADVANCE(37);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_data);
      if (lookahead == '?') ADVANCE(7);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '\'' &&
          lookahead != '+' &&
          lookahead != ':') ADVANCE(37);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_data);
      if (lookahead == '?') ADVANCE(7);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '\'' &&
          lookahead != '+' &&
          lookahead != ':') ADVANCE(37);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_data);
      if (lookahead == '?') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '\'' &&
          lookahead != '+' &&
          lookahead != ':') ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_data);
      if (lookahead == '?') ADVANCE(26);
      if (lookahead == '\r' ||
          lookahead == '\'' ||
          lookahead == '+' ||
          lookahead == ':') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(25);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_data);
      if (lookahead == '?') ADVANCE(10);
      if (lookahead == '\r' ||
          lookahead == '\'' ||
          lookahead == '+' ||
          lookahead == ':') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(40);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_data);
      if (lookahead == '?') ADVANCE(8);
      if (lookahead == '\r' ||
          lookahead == '\'' ||
          lookahead == '+' ||
          lookahead == ':') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(38);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_data);
      if (lookahead == '?') ADVANCE(12);
      if (lookahead == '\r' ||
          lookahead == '\'' ||
          lookahead == '+' ||
          lookahead == ':') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(42);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_data);
      if (lookahead == '?') ADVANCE(14);
      if (lookahead == '\r' ||
          lookahead == '\'' ||
          lookahead == '+' ||
          lookahead == ':') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_terminator);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 20},
  [2] = {.lex_state = 2},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 22},
  [8] = {.lex_state = 22},
  [9] = {.lex_state = 22},
  [10] = {.lex_state = 22},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 22},
  [24] = {.lex_state = 22},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 22},
  [27] = {.lex_state = 22},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_una_advice] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [sym_segment_tag] = ACTIONS(1),
    [sym_data] = ACTIONS(1),
    [sym_terminator] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(29),
    [sym_segment] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_una_advice] = ACTIONS(5),
    [sym_segment_tag] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(9), 1,
      anon_sym_COLON,
    ACTIONS(13), 1,
      sym_data,
    STATE(12), 1,
      sym_component,
    STATE(25), 1,
      sym_element,
    ACTIONS(11), 2,
      anon_sym_PLUS,
      sym_terminator,
  [17] = 5,
    ACTIONS(13), 1,
      sym_data,
    ACTIONS(15), 1,
      anon_sym_COLON,
    STATE(13), 1,
      aux_sym_element_repeat1,
    STATE(14), 1,
      sym_component,
    ACTIONS(17), 2,
      anon_sym_PLUS,
      sym_terminator,
  [34] = 5,
    ACTIONS(19), 1,
      anon_sym_COLON,
    ACTIONS(21), 1,
      anon_sym_PLUS,
    ACTIONS(23), 1,
      sym_terminator,
    STATE(5), 1,
      aux_sym_segment_repeat1,
    STATE(17), 1,
      aux_sym_segment_repeat2,
  [50] = 5,
    ACTIONS(19), 1,
      anon_sym_COLON,
    ACTIONS(21), 1,
      anon_sym_PLUS,
    ACTIONS(25), 1,
      sym_terminator,
    STATE(11), 1,
      aux_sym_segment_repeat1,
    STATE(19), 1,
      aux_sym_segment_repeat2,
  [66] = 3,
    ACTIONS(13), 1,
      sym_data,
    STATE(22), 1,
      sym_component,
    ACTIONS(27), 3,
      anon_sym_COLON,
      anon_sym_PLUS,
      sym_terminator,
  [78] = 3,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(31), 1,
      sym_segment_tag,
    STATE(10), 2,
      sym_segment,
      aux_sym_source_file_repeat1,
  [89] = 3,
    ACTIONS(31), 1,
      sym_segment_tag,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    STATE(10), 2,
      sym_segment,
      aux_sym_source_file_repeat1,
  [100] = 3,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(31), 1,
      sym_segment_tag,
    STATE(8), 2,
      sym_segment,
      aux_sym_source_file_repeat1,
  [111] = 3,
    ACTIONS(35), 1,
      ts_builtin_sym_end,
    ACTIONS(37), 1,
      sym_segment_tag,
    STATE(10), 2,
      sym_segment,
      aux_sym_source_file_repeat1,
  [122] = 3,
    ACTIONS(40), 1,
      anon_sym_COLON,
    STATE(11), 1,
      aux_sym_segment_repeat1,
    ACTIONS(43), 2,
      anon_sym_PLUS,
      sym_terminator,
  [133] = 3,
    ACTIONS(15), 1,
      anon_sym_COLON,
    STATE(13), 1,
      aux_sym_element_repeat1,
    ACTIONS(17), 2,
      anon_sym_PLUS,
      sym_terminator,
  [144] = 3,
    ACTIONS(15), 1,
      anon_sym_COLON,
    STATE(16), 1,
      aux_sym_element_repeat1,
    ACTIONS(45), 2,
      anon_sym_PLUS,
      sym_terminator,
  [155] = 3,
    ACTIONS(15), 1,
      anon_sym_COLON,
    STATE(15), 1,
      aux_sym_element_repeat1,
    ACTIONS(45), 2,
      anon_sym_PLUS,
      sym_terminator,
  [166] = 3,
    ACTIONS(15), 1,
      anon_sym_COLON,
    STATE(16), 1,
      aux_sym_element_repeat1,
    ACTIONS(47), 2,
      anon_sym_PLUS,
      sym_terminator,
  [177] = 3,
    ACTIONS(49), 1,
      anon_sym_COLON,
    STATE(16), 1,
      aux_sym_element_repeat1,
    ACTIONS(52), 2,
      anon_sym_PLUS,
      sym_terminator,
  [188] = 3,
    ACTIONS(21), 1,
      anon_sym_PLUS,
    ACTIONS(54), 1,
      sym_terminator,
    STATE(20), 1,
      aux_sym_segment_repeat2,
  [198] = 1,
    ACTIONS(56), 3,
      anon_sym_COLON,
      anon_sym_PLUS,
      sym_terminator,
  [204] = 3,
    ACTIONS(21), 1,
      anon_sym_PLUS,
    ACTIONS(58), 1,
      sym_terminator,
    STATE(20), 1,
      aux_sym_segment_repeat2,
  [214] = 3,
    ACTIONS(60), 1,
      anon_sym_PLUS,
    ACTIONS(63), 1,
      sym_terminator,
    STATE(20), 1,
      aux_sym_segment_repeat2,
  [224] = 1,
    ACTIONS(65), 3,
      anon_sym_COLON,
      anon_sym_PLUS,
      sym_terminator,
  [230] = 1,
    ACTIONS(52), 3,
      anon_sym_COLON,
      anon_sym_PLUS,
      sym_terminator,
  [236] = 1,
    ACTIONS(67), 2,
      ts_builtin_sym_end,
      sym_segment_tag,
  [241] = 1,
    ACTIONS(69), 2,
      ts_builtin_sym_end,
      sym_segment_tag,
  [246] = 1,
    ACTIONS(71), 2,
      anon_sym_PLUS,
      sym_terminator,
  [251] = 1,
    ACTIONS(73), 2,
      ts_builtin_sym_end,
      sym_segment_tag,
  [256] = 1,
    ACTIONS(75), 2,
      ts_builtin_sym_end,
      sym_segment_tag,
  [261] = 1,
    ACTIONS(77), 1,
      sym_data,
  [265] = 1,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 17,
  [SMALL_STATE(4)] = 34,
  [SMALL_STATE(5)] = 50,
  [SMALL_STATE(6)] = 66,
  [SMALL_STATE(7)] = 78,
  [SMALL_STATE(8)] = 89,
  [SMALL_STATE(9)] = 100,
  [SMALL_STATE(10)] = 111,
  [SMALL_STATE(11)] = 122,
  [SMALL_STATE(12)] = 133,
  [SMALL_STATE(13)] = 144,
  [SMALL_STATE(14)] = 155,
  [SMALL_STATE(15)] = 166,
  [SMALL_STATE(16)] = 177,
  [SMALL_STATE(17)] = 188,
  [SMALL_STATE(18)] = 198,
  [SMALL_STATE(19)] = 204,
  [SMALL_STATE(20)] = 214,
  [SMALL_STATE(21)] = 224,
  [SMALL_STATE(22)] = 230,
  [SMALL_STATE(23)] = 236,
  [SMALL_STATE(24)] = 241,
  [SMALL_STATE(25)] = 246,
  [SMALL_STATE(26)] = 251,
  [SMALL_STATE(27)] = 256,
  [SMALL_STATE(28)] = 261,
  [SMALL_STATE(29)] = 265,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_segment_repeat2, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_element_repeat1, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_segment_repeat1, 2, 0, 5), SHIFT_REPEAT(28),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_segment_repeat1, 2, 0, 5),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 2, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 3, 0, 0),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_element_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_element_repeat1, 2, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_segment_repeat1, 2, 0, 2),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_segment_repeat2, 2, 0, 7), SHIFT_REPEAT(2),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_segment_repeat2, 2, 0, 7),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_segment, 2, 0, 1),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_segment, 3, 0, 4),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_segment_repeat2, 2, 0, 3),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_segment, 3, 0, 6),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_segment, 4, 0, 8),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [79] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_edifact(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "edifact",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
